version: '3'

services:

  dash:
    build:
      context: ./rating_table
      dockerfile: Dockerfile
    container_name: dash
    ports:
      - "8080:8080"
    restart: always

  crawling:
    build:
      context: ./crawling
      dockerfile: Dockerfile
    container_name: crawling
    ports:
      - "8050:8050"
    depends_on:
      - dash
    restart: "no"

